---
# Software and configuration for working with Docker

- name: Add APT keys for Docker CE
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    keyserver: p80.pool.sks-keyservers.net
    keyring: /etc/apt/trusted.gpg.d/docker-ce.gpg
    state: present
  become: true

- name: Add APT source for Docker CE
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} nightly'
    filename: docker-ce
    state: present
  become: true

- name: Install system packages for working with Docker
  package: name={{ item }} state=present
  with_items:
    - docker-ce
    - docker-compose
  become: true

- name: Add user "{{ ansible_user_id }}" to docker group (requires log out/in again)
  command: adduser {{ ansible_user_id }} docker
  become: true

- name: Install Kompose (Compose->Kubernetes converter)
  get_url:
    url: https://github.com/kubernetes/kompose/releases/download/v1.11.0/kompose-linux-amd64
    dest: /usr/local/bin/kompose
    mode: 0755
  become: true
  tags:
    - kubernetes
