---
# Programmer's editors and IDEs

- name: Add APT keys for Visual Studio Code
  apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    state: present
  become: true
  tags:
    - vscode

- name: Add APT source for Visual Studio Code
  apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present
  become: true
  tags:
    - vscode

- name: Install popular IDEs
  package: name={{ item }} state=present
  with_items:
    #- atom
    - code
    - vim
  become: true
  tags:
    - vi
    - vscode

- name: Install popular extensions for Visual Studio Code
  command: code --install-extension "{{ item }}"
  with_items: '{{ editors_vscode_plugins }}'
  tags:
    - vscode

- name: Install various JetBrains IDEs
  command: snap install {{ item }} --classic
  with_items: '{{ editors_jetbrains_ides }}'
  become: true
  tags:
    - jetbrains

- name: Ensure reasonably high file watch limit for JetBrains IDEs
  lineinfile:
    dest: /etc/sysctl.d/60-jetbrains.conf
    create: true
    line: '{{ item }}'
  with_items:
    - '# Set inotify watch limit high enough for IntelliJ IDEA (PhpStorm, PyCharm, RubyMine, WebStorm).'
    - '# Source: https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit'
    - 'fs.inotify.max_user_watches = 524288'
  become: true
  tags:
    - jetbrains
