---
# Programmer's editors and IDEs

- name: Add APT keys for Visual Studio Code
  apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    state: present
  become: true

- name: Add APT source for Visual Studio Code
  apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
  become: true

- name: Install popular IDEs
  package: name={{ item }} state=present
  with_items:
    #- atom
    - code
    - vim
  become: true

- name: Install various JetBrains IDEs
  command: snap install {{ item }} --classic
  with_items:
    - intellij-idea-community
    - pycharm-community
  become: true
