---
# Programmer's editors and IDEs

- name: Add APT source for Visual Studio Code
  apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
  become: true

- name: Install popular IDEs
  package: name={{ item }} state=present
  with_items:
    #- atom
    - code
    - vim
  become: true

- name: Install various JetBrains IDEs
  command: snap install {{ item }} --classic
  with_items:
    - intellij-idea-community
    - pycharm-community
  become: true
