---
# Programmer's editors and IDEs

- name: Install popular IDEs
  command: snap install {{ item }} --classic
  with_items: '{{ editors_popular_ides }}'
  become: true
  tags:
    - atom
    - vscode

- name: Install popular extensions for Visual Studio Code
  command: code --install-extension "{{ item }}" --force
  with_items: '{{ editors_vscode_plugins }}'
  tags:
    - vscode

- name: Install various JetBrains IDEs
  command: snap install {{ item }} --classic
  with_items: '{{ editors_jetbrains_ides }}'
  become: true
  tags:
    - jetbrains

- name: Ensure reasonably high file watch limit for JetBrains IDEs
  lineinfile:
    dest: /etc/sysctl.d/60-jetbrains.conf
    create: true
    line: '{{ item }}'
  with_items:
    - '# Set inotify watch limit high enough for IntelliJ IDEA (PhpStorm, PyCharm, RubyMine, WebStorm).'
    - '# Source: https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit'
    - 'fs.inotify.max_user_watches = 524288'
  become: true
  tags:
    - jetbrains
