---
# Python tools and configuration (favoring Python 3, as it should be)

- name: Remove Python 2 Package Installer (pip)
  package: name=python-pip state=absent
  become: true

- name: Install Python 3 Package Installer (pip)
  package: name=python3-pip state=present
  become: true

- name: Install some awesome Python tools in user space
  pip: name={{ item }} executable=pip3 extra_args=--user state=present
  with_items:
    - pipenv

# - pyenv
