---
# Painless setup of your developer machine.
# (Especially if you're in DevOps and automation)
#
# How use it?
# 1. Ubuntu base setup (bonus: encrypt file system)
# 2. Install ansible (apt-get install ansible)
# 3. Run this playbook (ansible-playbook playbook.yml --ask-become-pass)

- name: Set up a sweet developer machine.
  hosts: localhost
  roles:
    - painless.software
  vars:
    HOSTNAME: '{{ ansible_hostname }}'
    FQDN: '{{ ansible_fqdn }}'
    DOMAIN: '{{ ansible_domain }}'
    IP_ADDRESS: '{{ ansible_default_ipv4.address }}'
