---
# Utilities used on the command line

- name: Install a few useful command line tools
  package: name={{ item }} state=present
  with_items:
    - dos2unix
    - ncdu
    - ssh
    - tmux
    - tree
    - whois
  become: true
  tags:
    - cli

- name: Ensure sane default settings for tmux
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.tmux.conf'
    create: true
    line: 'set -g mouse on'
  tags:
    - cli
