---
# Software and configuration for managing disks and volumes

- name: Install Etcher (SD card and USB drive burner)
  unarchive:
    remote_src: yes
    src: https://github.com/resin-io/etcher/releases/download/v1.3.1/etcher-1.3.1-linux-x86_64.zip
    dest: /opt/
    creates: /opt/etcher-1.3.1-x86_64.AppImage
  become: true
