---
# Software and configuration for managing disks and volumes

- name: Add APT keys for Etcher
  apt_key:
    id: 379CE192D401AB61
    keyserver: keyserver.ubuntu.com
    keyring: /etc/apt/trusted.gpg.d/ubuntu.gpg
    state: present
  become: true
  tags:
    - etcher

- name: Add APT source for Etcher
  apt_repository:
    repo: deb https://dl.bintray.com/resin-io/debian stable etcher
    filename: etcher
    state: present
  become: true
  tags:
    - etcher

- name: Install Etcher (SD card and USB drive burner)
  package: name=etcher-electron state=present
  become: true
  tags:
    - etcher
