---
# Software and configuration for network layer

- name: Install OpenVPN integration for Network Manager
  package: name={{ item }} state=present
  with_items:
    - network-manager-openvpn
    - network-manager-openvpn-gnome
  become: true
  tags:
    - office
    - vpn
