---
# Software and configuration for virtualization

- name: Install popular virtualization software and tools
  package: name={{ item }} state=present
  with_items:
    - libvirt-bin
    - virt-manager
    - virtualbox
    - vagrant
  become: true
  tags:
    - libvirt
    - virtualbox
    - vagrant

- name: Find out whether VMware Player is installed
  stat: path=/usr/bin/vmplayer
  register: vmware_installed
  changed_when: not vmware_installed.stat.exists
  tags:
    - vmware

- block:
    - name: Download VMware Player installer
      get_url:
        url: '{{ vmware_baseurl }}/{{ vmware_package }}'
        dest: '{{ vmware_installer }}'
        mode: 0755
    - name: Install VMware Player
      command: '{{ vmware_install_cmd }}'
  when: not vmware_installed.stat.exists or force_upgrade == 'yes'
  become: true
  tags:
    - vmware
