---
# Software and configuration for virtualization

- name: Install popular virtualization software and tools
  package: name={{ item }} state=present
  with_items:
    - virtualbox
  become: true

- name: Download VMware Player installer
  command: echo 'Not implemented yet'

- name: Install VMware Player
  command: echo 'Not implemented yet'
