---
# Software and configuration for virtualization

- name: Install popular virtualization software and tools
  package: name={{ item }} state=present
  with_items:
    - libvirt-bin
    - virtualbox
  become: true
  tags:
    - virtualization

- name: Download VMware Player installer
  get_url:
    url: '{{ vmware_baseurl }}/{{ vmware_package }}'
    dest: '{{ vmware_installer }}'
    mode: 0755
  become: true
  tags:
    - virtualization

- name: Install VMware Player
  command: '{{ vmware_install_cmd }}'
  # NOTE: This will make it difficult to upgrade to a newer version
  # (VMware-Player will need to be uninstalled prior to upgrade)
  creates: /usr/bin/vmplayer
  become: true
  tags:
    - virtualization
