---
# Learning resources for Python

- name: Tkinter Tk GUI Python 3 binding (for Python's turtle module)
  package:
    name: python3-tk
    state: present
  become: true
  tags:
    - python-edu

- name: Python Turtle
  block:

    - name: Install dependencies for PythonTurtle
      package:
        name: python3-wxgtk4.0
        state: present

    - name: Clone PythonTurtle source code
      git:
        repo: https://github.com/PythonTurtle/PythonTurtle.git
        dest: /opt/PythonTurtle
        depth: 1

    - name: Create desktop shortcut for PythonTurtle
      blockinfile:
        dest: /usr/share/applications/PythonTurtle.desktop
        create: true
        block: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Terminal=false
          Exec=python3 -m pythonturtle
          Path=/opt/PythonTurtle/
          Name=Python Turtle
          Comment=Learning environment for Python
          Icon=/opt/PythonTurtle/pythonturtle/resources/turtle.png

  become: true
  tags:
    - python-edu
