---
# Software and configuration to make your use of computers safer

- name: KeePassXC offline password manager
  package:
    name: keepassxc
    state: present
  become: true
  tags:
    - keepass

- name: Bitwarden password manager
  command: snap install bitwarden
  become: true
  tags:
    - bitwarden
