---
# Software and configuration to make your use of computers safer

- name: KeePassXC offline password manager
  command: snap install keepassxc
  become: true
  tags:
    - keepass

- name: Bitwarden password manager
  command: snap install bitwarden
  become: true
  tags:
    - bitwarden

- name: GNOME Authenticator
  command: flatpak install -y flathub com.github.bilelmoussaoui.Authenticator
  tags:
    - otp

- name: OAuthTool
  package: name=oathtool state=present
  become: true
  tags:
    - cli
