---
# Software and configuration to make your use of computers safer

- name: KeePassXC offline password manager
  snap:
    name: keepassxc
    state: present
  become: true
  tags:
    - keepass

- name: Bitwarden password manager
  snap:
    name: bitwarden
    state: present
  become: true
  tags:
    - bitwarden

- name: GNOME Authenticator
  flatpak:
    name: com.belmoussaoui.Authenticator
    state: present
  tags:
    - otp

- name: OAuthTool
  package:
    name: oathtool
    state: present
  become: true
  tags:
    - cli

- block:
    - name: Enable PPA for latest stable Wireshark
      apt_repository:
        repo: ppa:wireshark-dev/stable
        state: present

    - name: Install Wireshark
      package:
        name: wireshark
        state: present

  become: true
  tags:
    - wireshark
