---
# Virtual Private Network (VPN) software and configuration

- name: NordVPN
  block:

    - name: Signing key for NordVPN
      get_url:
        url: https://repo.nordvpn.com/gpg/nordvpn_public.asc
        keyring: /etc/apt/trusted.gpg.d/nordvpn.gpg
        mode: 0644
        force: "{{ 'yes' if state == 'latest' else 'no' }}"

    - name: Remove signing key for NordVPN
      file:
        dest: /etc/apt/trusted.gpg.d/nordvpn.gpg
        state: absent
      when: bool_state == 'absent'

    - name: APT source for NordVPN
      apt_repository:
        repo: 'deb https://repo.nordvpn.com/deb/nordvpn/debian stable main'
        filename: nordvpn
        state: '{{ bool_state }}'
        update_cache: "{{ bool_state == 'present' }}"

    - name: NordVPN client
      package:
        name: nordvpn
        state: '{{ state }}'

  become: true
  tags:
    - nordvpn
