---
# Virtual Private Network (VPN) software and configuration

- name: NordVPN
  block:

    - name: Signing key for NordVPN
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: BC5480EFEC5C081CE5BCFBE26B219E535C964CA1
        state: '{{ bool_state }}'

    - name: APT source for NordVPN
      apt_repository:
        repo: 'deb https://repo.nordvpn.com/deb/nordvpn/debian stable main'
        filename: nordvpn
        state: '{{ bool_state }}'
        update_cache: "{{ bool_state == 'present' }}"

    - name: NordVPN client
      package:
        name: nordvpn
        state: '{{ state }}'

  become: true
  tags:
    - nordvpn
