---
# Software and configuration for data backup and restore

- name: Déjà Dup (a backup/restore desktop application)
  package:
    name:
      - deja-dup
      - duplicity
      - python-gi
    state: '{{ bool_state }}'
  become: true
  tags:
    - backup
