---
# Software and configuration for data backup and restore

- name: Déjà Dup (a backup/restore desktop application)
  snap:
    name:
      - deja-dup
    classic: yes
    state: '{{ bool_state }}'
  become: true
  tags:
    - backup
