---
# Software for hardware info and benchmarking

- name: Install hardware info and benchmarking tools
  package:
    name:
      - hardinfo
      - lshw
    state: present
  become: true
  tags:
    - benchmark
