---
# Utilities used on the command line

- name: Install a few useful command line tools
  package:
    name:
      - dos2unix
      - httpie
      - lolcat
      - moreutils
      - ncdu
      - ssh
      - tmux
      - tree
      - vim
      - whois
      - xclip
    state: '{{ state }}'
  become: true
  tags:
    - cli

- name: Ensure sane default settings for tmux
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.tmux.conf'
    create: true
    line: 'set -g mouse on'
    state: '{{ bool_state }}'
  tags:
    - cli

- name: Provide some useful aliases
  block:

    - name: ip, ipb, open, pbcopy, pbpaste
      lineinfile:
        path: '{{ ansible_env.HOME }}/.bash_aliases'
        create: true
        line: '{{ item }}'
        state: '{{ bool_state }}'
      with_items:
        - "alias ip='ip --color'"
        - "alias ipb='ip --brief --color'"
        - "alias open='xdg-open'"
        - "alias pbcopy='xclip -selection clipboard'"
        - "alias pbpaste='xclip -selection clipboard -o'"

    - name: auto-tmux ssh
      blockinfile:
        path: '{{ ansible_env.HOME }}/.bash_aliases'
        create: true
        block: |
          # Auto open tmux in ssh sessions. Use `/usr/bin/ssh` for plain SSH.
          function ssh () {
            TERM=${TERM//-unicode-/-}
            TERM=${TERM//screen\./}
            /usr/bin/ssh -t $@ "tmux attach || tmux new || bash"
          }
        state: '{{ bool_state }}'

  tags:
    - cli
