---
# Software and configuration for network layer

- name: Install OpenVPN integration for Network Manager
  package:
    name:
      - network-manager-openvpn
      - network-manager-openvpn-gnome
    state: present
  become: true
  tags:
    - office
    - vpn
