---
# Software and configuration for network layer

- name: Install OpenVPN integration for Network Manager
  package:
    name:
      - network-manager-openvpn
      - network-manager-openvpn-gnome
    state: present
  become: true
  tags:
    - office
    - vpn

- name: Provide some useful aliases
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.bash_aliases'
    create: true
    line: '{{ item }}'
  with_items:
    - "alias ip='ip --color'"
    - "alias ipb='ip --brief --color'"
  tags:
    - cli
