---
# Software and configuration for network layer

- name: Install OpenVPN integration for Network Manager
  package:
    name:
      - network-manager-openvpn
      - network-manager-openvpn-gnome
    state: present
  become: true
  tags:
    - office
    - vpn

- name: Provide some useful aliases
  block:

    - name: ip, ipb
      lineinfile:
        path: '{{ ansible_env.HOME }}/.bash_aliases'
        create: true
        line: '{{ item }}'
      with_items:
        - "alias ip='ip --color'"
        - "alias ipb='ip --brief --color'"

    - name: auto-tmux ssh
      blockinfile:
        path: '{{ ansible_env.HOME }}/.bash_aliases'
        create: true
        block: |
          # Auto open tmux in ssh sessions. Use `/usr/bin/ssh` for plain SSH.
          function ssh () {
            TERM=${TERM//-unicode-/-}
            TERM=${TERM//screen\./}
            /usr/bin/ssh -t $@ "tmux attach || tmux new || bash"
          }

  tags:
    - cli
