---
# Software and configuration for virtualization

- name: libvirt (incl. virt-manager)
  package:
    name:
      - libvirt-bin
      - virt-manager
    state: '{{ state }}'
  become: true
  tags:
    - libvirt

- name: Install VirtualBox
  block:

    - name: Accept license for extension pack (preseeding)
      debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: 'true'
        vtype: select

    - name: VirtualBox and its extension pack
      package:
        name:
          - virtualbox
          - virtualbox-ext-pack
        state: '{{ state }}'

  become: true
  tags:
    - virtualbox

- name: Vagrant (instead of outdated package from system)
  block:

    - name: Signing key of Hashicorp packaging
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: '{{ bool_state }}'

    - name: APT source for Vagrant
      apt_repository:
        repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main'
        filename: hashicorp-vagrant
        state: '{{ bool_state }}'

    - name: Vagrant package from Hashicorp
      package:
        name: vagrant
        state: '{{ state }}'

  become: true
  tags:
    - vagrant

- name: Find out whether VMware Player is installed
  stat:
    path: /usr/bin/vmplayer
  register: vmware_player
  changed_when: not vmware_player.stat.exists
  tags:
    - vmware

- name: VMware Player
  block:

    - name: Uninstall VMware Player
      command: '{{ vmware_uninstall_cmd }}'
      when: state == 'absent' and vmware_player.stat.exists

    - name: Install or upgrade
      block:

        - name: Download VMware Player installer
          get_url:
            url: '{{ vmware_baseurl }}/{{ vmware_package }}'
            dest: '{{ vmware_installer }}'
            mode: 0755
            force: "{{ 'yes' if state == 'latest' else 'no' }}"

        - name: Install VMware Player
          command: '{{ vmware_install_cmd }}'

      when: state == 'present' and not vmware_player.stat.exists or state == 'latest'

  become: true
  tags:
    - vmware

- name: Citrix client
  block:

    - name: Find out whether Citrix client is installed
      stat:
        path: /opt/Citrix/ICAClient/selfservice
      register: citrix_installed

    - block:

        - name: Parse accept hash from Linux download overview
          ansible.builtin.shell:
            cmd: "wget -q -O- {{ citrix_overview_url }} | grep '{{ citrix_hash_start_marker }}' | sed -e 's/^.*{{ citrix_hash_start_marker }}//' -e 's/{{ citrix_hash_stop_marker }}.*$//' | uniq"
            warn: false
          register: citrix_accepthash

        - name: Install and configure Citrix
          block:

            - name: Citrix client (Workspace App)
              apt:
                deb: '{{ citrix_download_url }}'

            - name: Remove CA certs shipped by Citrix
              file:
                path: /opt/Citrix/ICAClient/keystore/cacerts
                state: absent

            - name: Ensure CA certificates (system)
              package:
                name: ca-certificates
                state: latest

            - name: Use installed CA certs with Citrix client
              file:
                src: /etc/ssl/certs
                path: /opt/Citrix/ICAClient/keystore/cacerts
                state: link

          become: true
      when: not citrix_installed.stat.exists or state == 'latest'

  tags:
    - citrix
