---
# Software and configuration for virtualization

- name: Install libvirt and virt-manager
  package:
    name:
      - libvirt-bin
      - virt-manager
    state: present
  become: true
  tags:
    - libvirt

- name: Install VirtualBox
  block:

    - name: Accept license for extension pack (preseeding)
      debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: 'true'
        vtype: select

    - name: Install VirtualBox and its extension pack
      package:
        name:
          - virtualbox
          - virtualbox-ext-pack
        state: present

  become: true
  tags:
    - virtualbox

- name: Vagrant (instead of outdated package from system)
  block:

    - name: Find out whether Vagrant is installed
      command: dpkg-query -W vagrant
      register: vagrant_installed
      failed_when: vagrant_installed.rc > 1
      changed_when: vagrant_installed.rc == 1

    - name: Install Vagrant from website
      apt: deb={{ vagrant_baseurl }}/{{ vagrant_package }}
      when: vagrant_installed.rc == 1 or force_upgrade == 'yes'
      become: true

  tags:
    - vagrant

- name: Find out whether VMware Player is installed
  stat: path=/usr/bin/vmplayer
  register: vmware_player
  changed_when: not vmware_player.stat.exists
  tags:
    - vmware

- block:
    - name: Download VMware Player installer
      get_url:
        url: '{{ vmware_baseurl }}/{{ vmware_package }}'
        dest: '{{ vmware_installer }}'
        mode: 0755
        force: '{{ force_upgrade }}'
    - name: Install VMware Player
      command: '{{ vmware_install_cmd }}'
  when: not vmware_player.stat.exists or force_upgrade == 'yes'
  become: true
  tags:
    - vmware
