---
# Software and configuration for virtualization

- name: Install libvirt and virt-manager
  package:
    name:
      - libvirt-bin
      - virt-manager
    state: present
  become: true
  tags:
    - libvirt

- name: Install VirtualBox
  block:

    - name: Accept license for extension pack (preseeding)
      debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: 'true'
        vtype: select

    - name: Install VirtualBox and its extension pack
      package:
        name:
          - virtualbox
          - virtualbox-ext-pack
        state: present

  become: true
  tags:
    - virtualbox

- name: Vagrant (instead of outdated package from system)
  block:

    - name: Signing key of Hashicorp packaging
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: APT source for Vagrant
      apt_repository:
        repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main'
        filename: hashicorp-vagrant
        state: present

    - name: Vagrant package from Hashicorp
      package:
        name: vagrant
        state: present

  become: true
  tags:
    - vagrant

- name: Find out whether VMware Player is installed
  stat: path=/usr/bin/vmplayer
  register: vmware_player
  changed_when: not vmware_player.stat.exists
  tags:
    - vmware

- block:
    - name: Download VMware Player installer
      get_url:
        url: '{{ vmware_baseurl }}/{{ vmware_package }}'
        dest: '{{ vmware_installer }}'
        mode: 0755
        force: '{{ force_upgrade }}'
    - name: Install VMware Player
      command: '{{ vmware_install_cmd }}'
  when: not vmware_player.stat.exists or force_upgrade == 'yes'
  become: true
  tags:
    - vmware
