---
# Software and configuration for virtualization

- name: Install libvirt and virt-manager
  package:
    name:
      - libvirt-bin
      - virt-manager
    state: present
  become: true
  tags:
    - libvirt

- name: Install VirtualBox
  block:

    - name: Accept license for extension pack (preseeding)
      debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: 'true'
        vtype: select

    - name: Install VirtualBox and its extension pack
      package:
        name:
          - virtualbox
          - virtualbox-ext-pack
        state: present

  become: true
  tags:
    - virtualbox

- name: Vagrant (instead of outdated package from system)
  block:

    - name: Signing key of Hashicorp packaging
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: APT source for Vagrant
      apt_repository:
        repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main'
        filename: hashicorp-vagrant
        state: present

    - name: Vagrant package from Hashicorp
      package:
        name: vagrant
        state: "{{ 'latest' if force_upgrade == 'yes' else 'present' }}"

  become: true
  tags:
    - vagrant

- name: Find out whether VMware Player is installed
  stat: path=/usr/bin/vmplayer
  register: vmware_player
  changed_when: not vmware_player.stat.exists
  tags:
    - vmware

- block:
    - name: Download VMware Player installer
      get_url:
        url: '{{ vmware_baseurl }}/{{ vmware_package }}'
        dest: '{{ vmware_installer }}'
        mode: 0755
        force: '{{ force_upgrade }}'
    - name: Install VMware Player
      command: '{{ vmware_install_cmd }}'
  when: not vmware_player.stat.exists or force_upgrade == 'yes'
  become: true
  tags:
    - vmware

- name: Citrix client
  block:

    - name: Find out whether Citrix client is installed
      stat: path=/opt/Citrix/ICAClient/selfservice
      register: citrix_installed

    - block:

        - name: Parse accept hash from Linux download overview
          ansible.builtin.shell:
            cmd: "curl -s {{ citrix_overview_url }} | grep '{{ citrix_hash_start_marker }}' | sed -e 's/^.*{{ citrix_hash_start_marker }}//' -e 's/{{ citrix_hash_stop_marker }}.*$//' | uniq"
            warn: false
          register: citrix_accepthash

        - block:

            - name: Install Citrix client (Workspace App)
              apt: deb={{ citrix_download_url }}

            - name: Ensure CA certificates for Citrix client
              package:
                name: ca-certificates
                state: present

            - name: Use installed CA certs with Citrix client
              file:
                src: /etc/ssl/certs
                path: /opt/Citrix/ICAClient/keystore/cacerts
                state: link
                follow: no
                force: yes

          become: true
      when: not citrix_installed.stat.exists or force_upgrade == 'yes'

  tags:
    - citrix
