---
# Software and configuration for virtualization

- name: Install popular virtualization software and tools
  package:
    name:
      - libvirt-bin
      - virt-manager
      - virtualbox
    state: present
  become: true
  tags:
    - libvirt
    - virtualbox


- name: Vagrant (instead of outdated package from system)
  block:

    - name: Find out whether Vagrant is installed
      command: dpkg-query -W vagrant
      register: vagrant_installed
      failed_when: vagrant_installed.rc > 1
      changed_when: vagrant_installed.rc == 1

    - name: Install Vagrant from website
      apt: deb={{ vagrant_baseurl }}/{{ vagrant_package }}
      when: vagrant_installed.rc == 1 or force_upgrade == 'yes'
      become: true

  tags:
    - vagrant

- name: Find out whether VMware Player is installed
  stat: path=/usr/bin/vmplayer
  register: vmware_player
  changed_when: not vmware_player.stat.exists
  tags:
    - vmware

- block:
    - name: Download VMware Player installer
      get_url:
        url: '{{ vmware_baseurl }}/{{ vmware_package }}'
        dest: '{{ vmware_installer }}'
        mode: 0755
    - name: Install VMware Player
      command: '{{ vmware_install_cmd }}'
  when: not vmware_player.stat.exists or force_upgrade == 'yes'
  become: true
  tags:
    - vmware
