---
# Software for your communication needs

- name: Cryptography, calendar and tasks support for Thunderbird
  package:
    name:
      - enigmail
      - xul-ext-lightning
    state: present
  become: true
  tags:
    - email

- name: Install popular chat clients (snaps)
  command: snap install {{ item }} --classic
  with_items:
    - rocketchat-desktop
    - skype
    - slack
  become: true
  tags:
    - rocketchat
    - skype
    - slack

- name: Install Rambox multi-messenger
  command: snap install rambox
  become: true
  tags:
    - rambox

- name: Ferdi multi-messenger
  block:

    - name: Find out whether Ferdi multi-messenger is installed
      command: dpkg-query -W ferdi
      register: ferdi_installed
      failed_when: ferdi_installed.rc > 1
      changed_when: ferdi_installed.rc == 1

    - name: Install Ferdi multi-messenger
      apt: deb={{ ferdi_baseurl }}/{{ ferdi_package }}
      when: ferdi_installed.rc == 1 or force_upgrade == 'yes'
      become: true

  tags:
    - ferdi
    - franz

- name: Signal for Desktop
  block:

    - name: Add signing key of Signal packaging
      apt_key:
        url: https://updates.signal.org/desktop/apt/keys.asc
        state: present

    - name: Add APT source for Signal deb package
      apt_repository:
        repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
        filename: signal-xenial
        update_cache: true
        state: present

    - name: Install Signal for Desktop
      package:
        name: signal-desktop
        state: present

  become: true
  tags:
    - signal

- name: Mircosoft Teams
  block:

    - name: Add signing key of Mircosoft packaging
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add APT source for Teams deb package
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
        filename: teams
        update_cache: true
        state: present

    - name: Install Mircosoft Teams
      package:
        name: teams
        state: present

  become: true
  tags:
    - teams

- name: Zoom conferencing
  block:

    - name: Find out whether Zoom conferencing client is installed
      command: dpkg-query -W zoom
      register: zoom_installed
      failed_when: zoom_installed.rc > 1
      changed_when: zoom_installed.rc == 1

    - name: Install Zoom conferencing client
      apt: deb=https://zoom.us/client/latest/zoom_amd64.deb
      when: zoom_installed.rc == 1 or force_upgrade == 'yes'
      become: true

  tags:
    - zoom
