---
# Software for your communication needs

- name: Cryptography, calendar and tasks support for Thunderbird
  package:
    name:
      - enigmail
      - xul-ext-lightning
    state: present
  become: true
  tags:
    - email

- name: Slack chat client (unconfined)
  snap:
    name: slack
    classic: yes
    state: present
  become: true
  tags:
    - slack

- name: Ferdi multi-messenger client (Franz free/libre)
  snap:
    name: ferdi
    state: present
  become: true
  tags:
    - ferdi
    - franz

- name: Rambox multi-messenger client
  snap:
    name: rambox
    state: present
  become: true
  tags:
    - rambox

- name: RocketChat messaging client
  snap:
    name: rocketchat-desktop
    state: present
  become: true
  tags:
    - rocketchat

- name: Signal messaging for Desktop
  snap:
    name: signal-desktop
    state: present
  become: true
  tags:
    - signal

- name: Skype messaging client
  snap:
    name: skype
    state: present
  become: true
  tags:
    - skype

- name: Mircosoft Teams client
  snap:
    name: teams
    state: present
  become: true
  tags:
    - teams

- name: Zoom conferencing client
  snap:
    name: zoom-client
    state: present
  become: true
  tags:
    - zoom
