---
# Software for your communication needs

- name: Cryptography, calendar and tasks support for Thunderbird
  package:
    name:
      - enigmail
      - xul-ext-lightning
    state: '{{ state }}'
  become: true
  tags:
    - email

- name: Element (official Matrix client)
  block:

    - name: Signing key for Element packages
      apt_key:
        url: https://packages.element.io/debian/element-io-archive-keyring.gpg
        keyring: /etc/apt/trusted.gpg.d/element-io.gpg
        state: '{{ bool_state }}'

    - name: Remove signing key for Element packages
      file:
        dest: /etc/apt/trusted.gpg.d/element-io.gpg
        state: absent
      when: bool_state == 'absent'

    - name: APT source for Element
      apt_repository:
        repo: 'deb https://packages.element.io/debian/ default main'
        filename: element-io
        state: '{{ bool_state }}'

    - name: Element Desktop
      package:
        name: element-desktop
        state: '{{ state }}'

  become: true
  tags:
    - matrix

- name: Discord desktop client
  snap:
    name: discord
    state: '{{ bool_state }}'
  become: true
  tags:
    - discord

- name: Slack chat client (unconfined)
  snap:
    name: slack
    classic: yes
    state: '{{ bool_state }}'
  become: true
  tags:
    - slack

- name: Ferdium multi-messenger client (Franz/Ferdi free/libre)
  snap:
    name: ferdium
    state: '{{ bool_state }}'
  become: true
  tags:
    - ferdi
    - franz

- name: Rambox multi-messenger client
  snap:
    name: rambox
    state: '{{ bool_state }}'
  become: true
  tags:
    - rambox

- name: RocketChat messaging client
  snap:
    name: rocketchat-desktop
    state: '{{ bool_state }}'
  become: true
  tags:
    - rocketchat

- name: Signal messaging for Desktop
  snap:
    name: signal-desktop
    state: '{{ bool_state }}'
  become: true
  tags:
    - signal

- name: Skype messaging client
  snap:
    name: skype
    state: '{{ bool_state }}'
  become: true
  tags:
    - skype

- name: Telegram desktop client
  snap:
    name: telegram-desktop
    state: '{{ bool_state }}'
  become: true
  tags:
    - telegram

- name: Mircosoft Teams client
  snap:
    name: teams-for-linux
    state: '{{ bool_state }}'
  become: true
  tags:
    - teams

- name: WhatsApp client (Whatsie)
  snap:
    name: whatsie
    state: '{{ bool_state }}'
  become: true
  tags:
    - whatsapp

- name: Zoom conferencing client
  snap:
    name: zoom-client
    state: '{{ bool_state }}'
  become: true
  tags:
    - zoom

- name: Webex
  block:

    - name: Find out whether Webex is installed
      command: dpkg-query -W webex
      register: webex_installed
      failed_when: webex_installed.rc > 1
      changed_when: webex_installed.rc == 1

    - block:

        - name: Uninstall Webex
          package:
            name:
              - webex
            state: absent
          when: bool_state == 'absent'

        - name: Webex (download from website)
          apt:
            deb: https://binaries.webex.com/WebexDesktop-Ubuntu-Official-Package/Webex.deb
          when: webex_installed.rc == 1 or state == 'latest'

      become: true

  tags:
    - webex
