---
# Software for your communication needs

- name: Cryptography, calendar and tasks support for Thunderbird
  package:
    name:
      - enigmail
      - xul-ext-lightning
    state: present
  become: true
  tags:
    - email

- name: Install popular chat clients (snaps)
  command: snap install {{ item }} --classic
  with_items:
    - rocketchat-desktop
    - skype
    - slack
  become: true
  tags:
    - rocketchat
    - skype
    - slack

- name: Install Rambox multi-messenger
  command: snap install rambox
  become: true
  tags:
    - rambox

- name: Ferdi multi-messenger
  block:

    - name: Find out whether Ferdi multi-messenger is installed
      command: dpkg-query -W ferdi
      register: ferdi_installed
      failed_when: ferdi_installed.rc > 1
      changed_when: ferdi_installed.rc == 1

    - name: Install Ferdi multi-messenger
      apt: deb={{ ferdi_baseurl }}/{{ ferdi_package }}
      when: ferdi_installed.rc == 1 or force_upgrade == 'yes'
      become: true

  tags:
    - ferdi
    - franz

- name: Zoom conferencing
  block:

    - name: Find out whether Zoom conferencing client is installed
      command: dpkg-query -W zoom
      register: zoom_installed
      failed_when: zoom_installed.rc > 1
      changed_when: zoom_installed.rc == 1

    - name: Install Zoom conferencing client
      apt: deb=https://zoom.us/client/latest/zoom_amd64.deb
      when: zoom_installed.rc == 1 or force_upgrade == 'yes'
      become: true

  tags:
    - zoom
