---
# Software for your communication needs

- name: Cryptography, calendar and tasks support for Thunderbird
  package:
    name:
      - enigmail
      - xul-ext-lightning
    state: present
  become: true
  tags:
    - email

- name: Install Slack chat clients (unconfined snap)
  snap:
    name: slack
    classic: yes
    state: present
  become: true
  tags:
    - slack

- name: Install popular chat clients (snaps)
  snap:
    name:
      - ferdi
      - rambox
      - rocketchat-desktop
      - skype
      - teams
    state: present
  become: true
  tags:
    - ferdi
    - franz
    - rambox
    - rocketchat
    - skype
    - teams

- name: Signal for Desktop
  snap:
    name: signal-desktop
    state: present
  become: true
  tags:
    - signal

- name: Zoom conferencing
  snap:
    name: zoom-client
    state: present
  become: true
  tags:
    - zoom
