---
# Software and configuration to tweak your desktop environment

- name: Install desktop customization tools
  package:
    name:
      - gnome-tweak-tool
      - dconf-editor
      - chrome-gnome-shell
    state: present
  become: true
  tags:
    - gnome

- name: GNOME Shell extension installer
  block:

    - name: Install dependencies for extension installer
      package: name=curl state=present

    - name: Install GNOME Shell extension installer
      get_url:
        url: https://raw.githubusercontent.com/brunelli/gnome-shell-extension-installer/master/gnome-shell-extension-installer
        dest: /usr/local/bin/gnome-shell-extension-installer
        mode: 0755

    - name: Install prerequisites for system monitor extension
      package:
        name:
          - gir1.2-gtop-2.0
          - gir1.2-networkmanager-1.0
          - gir1.2-clutter-1.0
        state: present

  become: true
  tags:
    - gnome
    - unity

- name: Userdefaults scripts
  block:

    - name: Ensure target directory for userdefaults
      file:
        path: "/opt/{{ userdefaults_organization }}"
        state: directory

    - name: Copy userdefaults scripts
      copy: src={{ item.src }} dest={{ item.dest }} mode='755'
      with_items:
        - src: files/base/desktop/userdefaults.sh
          dest: "/opt/{{ userdefaults_organization }}/userdefaults.sh"
        - src: files/base/desktop/userdefaults.d/
          dest: "/opt/{{ userdefaults_organization }}/userdefaults.d"

    - name: Install userdefaults script
      file:
        src: "/opt/{{ userdefaults_organization }}/userdefaults.sh"
        dest: "/usr/local/bin/{{ userdefaults_organization }}-userdefaults"
        state: link

  become: true
  tags:
    - gnome
    - unity
