---
# Software and configuration to tweak your desktop environment

- name: Install desktop customization tools
  package:
    name:
      - gnome-tweaks
      - dconf-editor
      - chrome-gnome-shell
    state: present
  become: true
  tags:
    - gnome

- name: GNOME Shell extensions
  block:

    # see https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/474
    - name: Ensure system monitor is not installed via snap
      snap:
        name: gnome-system-monitor
        state: absent

    - name: Ensure prerequisites for system monitor extension
      package:
        name:
          - gir1.2-clutter-1.0
          - gir1.2-gtop-2.0
          - gir1.2-nm-1.0
          - gnome-system-monitor
        state: '{{ state }}'

    - name: Install GNOME Shell extension manage CLI
      get_url:
        url: https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/gnomeshell-extension-manage
        dest: /usr/local/bin/gnome-shell-extension-manage
        mode: 0755
        force: "{{ 'yes' if state == 'latest' else 'no' }}"

    - name: Install useful GNOME Shell extensions system-wide
      command: "gnome-shell-extension-manage --install --system --extension-id {{ item }} --version latest"
      with_items: "{{ desktop_gnomeshell_extensions }}"

  become: true
  tags:
    - gnome
    - unity

- name: Userdefaults scripts
  block:

    - name: Ensure target directory for userdefaults
      file:
        path: "/opt/{{ userdefaults_organization }}"
        state: directory

    - name: Copy userdefaults scripts
      copy: src={{ item.src }} dest={{ item.dest }} mode='755'
      with_items:
        - src: files/base/desktop/userdefaults.sh
          dest: "/opt/{{ userdefaults_organization }}/userdefaults.sh"
        - src: files/base/desktop/userdefaults.d/
          dest: "/opt/{{ userdefaults_organization }}/userdefaults.d/"

    - name: Install userdefaults script
      file:
        src: "/opt/{{ userdefaults_organization }}/userdefaults.sh"
        dest: "/usr/local/bin/{{ userdefaults_organization }}-userdefaults"
        state: link

  become: true
  tags:
    - gnome
    - unity
