---
# Driver software and configuration for various devices

- name: DisplayLink USB adapter (USB 2.0 -> HDMI/VGA/RJ45/USB 2.0)
  block:

    - name: Ensure pre-requisites for DisplayLink adapter
      package:
        name: dkms
        state: present

    - name: Download DisplayLink script -- Run /opt/displaylink-debian.sh manually!
      get_url:
        url: https://raw.githubusercontent.com/AdnanHodzic/displaylink-debian/master/displaylink-debian.sh
        dest: /opt/displaylink-debian.sh
        mode: 0755
        force: "{% 'yes' if state == 'latest' else 'no' %}"

  become: true
  tags:
    - dell
    - displaylink-adapter
