---
# The base system (of a modern Linux distribution)

- name: Update APT cache before starting
  apt: update_cache=yes upgrade=no
  become: true

- block:

    - name: Install Flatpak package manager
      package:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: present
      become: true

    - name: Add default repository for Flatpak (flathub)
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  tags:
    - flatpak

- import_tasks: desktop.yml
- import_tasks: webbrowsers.yml
- import_tasks: communication.yml
- import_tasks: tablet.yml
- import_tasks: printers.yml
- import_tasks: devices.yml
