---
# The base system (of a modern Linux distribution)

- import_tasks: packagemanagers.yml
- import_tasks: desktop.yml
- import_tasks: webbrowsers.yml
- import_tasks: communication.yml
- import_tasks: tablet.yml
- import_tasks: pim.yml
- import_tasks: printers.yml
- import_tasks: devices.yml
