---
# The base system (of a modern Linux distribution)

- name: Update APT cache before starting
  apt: update_cache=yes upgrade=no
  become: true

- name: Install Flatpak package manager
  package:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
    state: present
  become: true
  tags:
    - flatpak

- import_tasks: desktop.yml
- import_tasks: webbrowsers.yml
- import_tasks: communication.yml
- import_tasks: tablet.yml
- import_tasks: pim.yml
- import_tasks: printers.yml
- import_tasks: devices.yml
