---
# Software and configuration for Personal Information Management (PIM)

- name: GNOME common apps (compatible snap version)
  snap:
    name: '{{ item }}'
    state: '{{ bool_state }}'
  loop:
    - gnome-calendar
    - gnome-contacts
  become: true
  tags:
    - gnome
    - calendar
    - contacts

- name: GNOME common apps (latest version via flatpak)
  flatpak:
    name: '{{ item }}'
    state: '{{ bool_state }}'
  loop:
    - org.gnome.Geary
    - org.gnome.Maps
  become: true
  tags:
    - gnome
    - email
    - maps
