---
# Software and configuration for Personal Information Management (PIM)

- name: GNOME common apps (remove snaps)
  snap:
    name: '{{ item }}'
    state: absent
  loop:
    - gnome-calendar
    - gnome-contacts
  become: true
  tags:
    - gnome
    - calendar
    - contacts

- name: GNOME common apps (flatpak)
  flatpak:
    name: '{{ item }}'
    state: '{{ bool_state }}'
  loop:
    - org.gnome.Calendar
    - org.gnome.Contacts
    - org.gnome.Geary
    - org.gnome.Maps
  become: true
  tags:
    - gnome
    - calendar
    - contacts
    - email
    - maps

# provides scanner integration out-of-the-box (unlike Flatpak)
- name: GNOME Document Management
  package:
    name:
      - paperwork-gtk
      - paperwork-gtk-l10n-de
      - paperwork-gtk-l10n-en
      - paperwork-shell
  become: true
  tags:
    - gnome
    - documents
