---
# Software and configuration for Personal Information Management (PIM)

- name: GNOME common apps (latest versions)
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - org.gnome.Calendar
    - org.gnome.Contacts
    - org.gnome.Geary
    - org.gnome.Maps
  become: true
  tags:
    - gnome
    - calendar
    - contacts
    - email
    - maps
