---
# Software and configuration for Personal Information Management (PIM)

- name: GNOME common apps (compatible snap version)
  community.general.snap:
    name:
      - gnome-calendar
      - gnome-contacts
    state: present
  become: true
  tags:
    - gnome
    - calendar
    - contacts

- name: GNOME common apps (latest version via flatpak)
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - org.gnome.Geary
    - org.gnome.Maps
  become: true
  tags:
    - gnome
    - email
    - maps
