---
# Driver software and configuration for printers, scanners, MFPs

- name: GNOME Document Scanner (flatpak)
  flatpak:
    name: org.gnome.SimpleScan
    state: '{{ bool_state }}'
  become: true
  tags:
    - gnome
    - epson-scanner
    - samsung-printer

- name: EPSON Scan 2, https://support.epson.net/linux/en/epsonscan2.php
  block:

    - name: Find out whether EPSON Scan 2 plugin already installed
      command: dpkg-query -W epsonscan2-non-free-plugin
      register: epsonscan_installed
      failed_when: epsonscan_installed.rc > 1
      changed_when: epsonscan_installed.rc == 1

    - name: Uninstall EPSON Scan 2 plugin
      package:
        name: epsonscan2-non-free-plugin
        state: "{{ state }}"
        purge: yes
      when: state == 'absent'

    - name: Download and install EPSON Scan 2 plugin
      block:

        - name: Download and extract EPSON Scan 2 bundle
          unarchive:
            remote_src: yes
            src: "{{ epsonscan_download_url }}"
            dest: /tmp/

        - name: Install EPSON Scan 2 plugin (for use by SimpleScan)
          apt:
            deb: "/tmp/{{ epsonscan_bundle }}/plugins/{{ epsonscan_plugin_deb }}"

      when: (epsonscan_installed.rc == 1 or state == 'latest') and state != 'absent'

  become: true
  tags:
    - epson-scanner

- name: Samsung MFP printer + scanner, https://www.bchemnet.com/suldr/
  block:

    - name: Find out whether suldr-keyring is installed
      command: dpkg-query -W suldr-keyring
      register: suldrkeyring_installed
      failed_when: suldrkeyring_installed.rc > 1
      changed_when: suldrkeyring_installed.rc == 1

    - name: APT keyring for SULD
      apt:
        deb: https://www.bchemnet.com/suldr/pool/debian/extra/su/suldr-keyring_2_all.deb
      when: suldrkeyring_installed.rc == 1

    - name: Add APT source for SULD
      apt_repository:
        repo: deb https://www.bchemnet.com/suldr/ debian extra
        filename: samsung-unified-driver
        update_cache: true
        state: '{{ bool_state }}'

    - name: Samsung Unified Linux Driver (SULD)
      package:
        name: suld-driver2-1.00.39
        state: '{{ state }}'

  become: true
  tags:
    - samsung-printer
