---
# Driver software and configuration for printers, scanners, MFPs

- name: EPSON Image Scan v3, https://support.epson.net/linux/en/iscan_c.html
  block:

    - name: Find out whether Image Scan v3 already installed
      command: dpkg-query -W imagescan
      register: imagescan_installed
      failed_when: imagescan_installed.rc > 1
      changed_when: imagescan_installed.rc == 1

    - name: Download and extract Image Scan package
      unarchive:
        remote_src: yes
        src: "{{ imagescan_download_base }}/{{ imagescan_download_path }}"
        dest: /tmp/
      when: imagescan_installed.rc == 1 or state == 'latest'

    - name: Ensure prerequisites for Image Scan v3
      package:
        name: graphicsmagick
        state: present

    - name: Install EPSON Image Scan v3
      apt:
        deb: '{{ item }}'
      with_items:
        - "/tmp/{{ imagescan_archive }}/core/imagescan_{{ imagescan_version }}-{{ imagescan_deb_tail }}"
        - "/tmp/{{ imagescan_archive }}/plugins/imagescan-plugin-gt-s650_{{ imagescan_plugin_gt_version }}-{{ imagescan_deb_tail }}"
        - "/tmp/{{ imagescan_archive }}/plugins/imagescan-plugin-ocr-engine_{{ imagescan_plugin_ocr_version }}-{{ imagescan_deb_tail }}"
        - "/tmp/{{ imagescan_archive }}/plugins/imagescan-plugin-networkscan_{{ imagescan_plugin_networkscan_version }}-{{ imagescan_deb_tail }}"
      when: imagescan_installed.rc == 1 or state == 'latest'

    - name: Configure EPSON scanner via Image Scan v3
      lineinfile:
        path: /etc/imagescan/imagescan.conf
        line: "{{ item }}"
      with_items:
        - "myscanner.udi    = esci:networkscan://{{ epson_printer_hostname }}:1865"
        - 'myscanner.vendor = Epson'
        - "myscanner.model  = {{ epson_printer_model }}"

  become: true
  tags:
    - epson-scanner

- name: Samsung MFP printer + scanner, https://www.bchemnet.com/suldr/
  block:

    - name: Find out whether suldr-keyring is installed
      command: dpkg-query -W suldr-keyring
      register: suldrkeyring_installed
      failed_when: suldrkeyring_installed.rc > 1
      changed_when: suldrkeyring_installed.rc == 1

    - name: APT keyring for SULD
      apt:
        deb: https://www.bchemnet.com/suldr/pool/debian/extra/su/suldr-keyring_2_all.deb
      when: suldrkeyring_installed.rc == 1

    - name: Add APT source for SULD
      apt_repository:
        repo: deb https://www.bchemnet.com/suldr/ debian extra
        filename: samsung-unified-driver
        update_cache: true
        state: '{{ bool_state }}'

    - name: Samsung Unified Linux Driver (SULD)
      package:
        name: suld-driver2-1.00.39
        state: '{{ state }}'

  become: true
  tags:
    - samsung-printer
