---
# Software and configuration for tablets and 2-in-1 convertibles

- name: Xournal++ handwriting app
  flatpak:
    name: com.github.xournalpp.xournalpp
    state: '{{ bool_state }}'
  become: true
  tags:
    - touch
    - xournal

- block:
  - name: Prerequisites for Write handwriting app
    package:
      name:
        - libqt5widgets5
        - libqt5network5
        - libqt5svg5
      state: '{{ state }}'

  - name: Write handwriting app
    unarchive:
      src: http://www.styluslabs.com/download/write-tgz
      remote_src: true
      dest: /opt
      creates: /opt/Write/Write
      owner: root
      group: root

  - name: Symlink for Write handwriting app
    file:
      src: /opt/Write/Write
      dest: /usr/local/bin/Write
      state: link

  - name: Desktop shortcut for Write handwriting
    blockinfile:
      dest: /usr/share/applications/Write.desktop
      create: true
      block: |
        [Desktop Entry]
        Version=1.0
        Type=Application
        Terminal=false
        Exec=/usr/local/bin/Write
        Name=Write
        Comment=Write handwriting
        Icon=

  become: true
  tags:
    - touch
    - write
