---
# Software you need for consuming Web contents

- name: Webbrowsers
  block:

    - name: Firefox
      block:

        - name: Avoid duplicate installs (Firefox deb)
          package:
            name: firefox
            state: absent
          when: bool_state == 'present'

        - name: Avoid duplicate installs (Firefox snap)
          snap:
            name: firefox
            state: absent

        - name: Firefox Web browser (flatpak)
          flatpak:
            name: org.mozilla.firefox
            state: '{{ bool_state }}'

        - name: Create or remove Firefox launcher
          file:
            path: /usr/bin/firefox
            mode: '755'
            state: "{{ 'file' if bool_state == 'present' else 'absent' }}"

        - name: Configure Firefox launcher
          copy:
            dest: /usr/bin/firefox
            content: |
              flatpak run org.mozilla.firefox "$@"
          when: bool_state == 'present'

      tags:
        - firefox

    - name: Chromium
      block:

        - name: Avoid duplicate installs (Chromium deb)
          package:
            name: chromium-browser
            state: absent
          when: bool_state == 'present'

        - name: Chromium Web browser (snap)
          snap:
            name: chromium
            state: '{{ bool_state }}'

      tags:
        - chromium

    - name: Opera Web browser (snap)
      snap:
        name: opera
        state: '{{ bool_state }}'
      tags:
        - opera

    - name: Brave Web browser (snap)
      snap:
        name: brave
        state: '{{ bool_state }}'
      tags:
        - opera

  become: true
  tags:
    - webbrowsers
