---
# Software you need for consuming Web contents

- block:
    - name: Avoid duplicate installs of Firefox (snap)
      command: snap remove firefox

    - name: Install Firefox Web browser
      package:
        name:
          - firefox
        state: present

  become: true
  tags:
    - firefox
    - webbrowsers

- block:
    - name: Avoid duplicate installs of Chromium (snap)
      command: snap remove chromium

    - name: Avoid duplicate installs of Chromium (deb)
      package:
        name:
          - chromium-browser
        state: absent

    - name: Enable PPA for ungoogled Chromium
      apt_repository:
        repo: ppa:braewoods/ungoogled-chromium
        state: present

    - name: Install ungoogled Chromium
      package:
        name:
          - ungoogled-chromium
        state: present

  become: true
  tags:
    - chromium
    - webbrowsers
