---
# Software you need for consuming Web contents

- block:
  - name: Popular Web browsers (avoid duplicate installs)
    command: snap remove {{ item }}
    with_items:
      - chromium
      - firefox

  - name: Install popular Web browsers
    package:
      name:
        - chromium-browser
        - firefox
      state: present

  become: true
  tags:
    - webbrowsers
