---
# Software you need for consuming Web contents

- block:
  - name: Popular Web browsers (avoid duplicate installs)
    package:
      name:
        - chromium-browser
        - firefox
      state: absent

  - name: Install popular Web browsers (snaps)
    command: snap install {{ item }}
    with_items:
      - chromium
      - firefox

  become: true
  tags:
    - webbrowsers
