---
# Software you need for consuming Web contents

- name: Webbrowsers
  block:

    - name: Firefox
      block:

        - name: Avoid duplicate installs (Firefox deb)
          package:
            name: firefox
            state: absent
          when: bool_state == 'present'

        - name: Firefox Web browser (snap)
          snap:
            name: firefox
            state: '{{ bool_state }}'

      tags:
        - firefox

    - name: Chromium
      block:

        - name: Avoid duplicate installs (Chromium deb)
          package:
            name: chromium-browser
            state: absent
          when: bool_state == 'present'

        - name: Chromium Web browser (snap)
          snap:
            name: chromium
            state: '{{ bool_state }}'

      tags:
        - chromium

    - name: Opera Web browser (snap)
      snap:
        name: opera
        state: '{{ bool_state }}'
      tags:
        - opera

    - name: Brave Web browser (snap)
      snap:
        name: brave
        state: '{{ bool_state }}'
      tags:
        - opera

  become: true
  tags:
    - webbrowsers
