---
# API browsers and debugging tools

- name: Install Insomnia REST client and command line tools
  command: snap install {{ item }}
  with_items:
    - insomnia
    - jq
  become: true
  tags:
    - restapi
