---
# API browsers and debugging tools

- name: Install Insomnia REST client and command line tools
  community.general.snap:
    name: '{{ item }}'
    state: present
  loop:
    - insomnia
    - jq
    - yq
  become: true
  tags:
    - restapi
