---
# API browsers and debugging tools

- name: Insomnia REST client and command line tools
  snap:
    name: '{{ item }}'
    state: '{{ bool_state }}'
  loop:
    - insomnia
    - jq
    - yq
  become: true
  tags:
    - restapi
