---
# Software and configuration for automation ninjas

- name: Puppet development tool chain
  block:

  - name: Find out whether APT key and sources for PDK are installed
    command: dpkg-query -W puppet-release
    register: puppet_pdk_installed
    failed_when: puppet_pdk_installed.rc > 1
    changed_when: puppet_pdk_installed.rc == 1

  - name: Install APT key and sources for PDK (Puppet 5)
    apt:
      deb: https://apt.puppetlabs.com/puppet-release-bionic.deb
      state: present
    when: puppet_pdk_installed.rc == 1

  - name: Install Puppet developer packages
    package:
      name:
        - puppet
        - pdk
      state: present
      update_cache: true

  become: true
  tags:
    - puppet

- name: Install Ansible developer packages
  package:
    name:
      - ansible
      - ansible-tower-cli
    state: present
  tags:
    - ansible
