---
# Software and configuration for automation ninjas

- name: Ansible developer tools (awx-cli)
  pip:
    name: ansible-tower-cli
    state: '{{ state }}'
  become: true
  tags:
    - ansible

- name: Puppet development tool chain
  block:

    - name: Find out whether APT key and sources for Puppet are installed
      command: dpkg-query -W puppet7-release
      register: puppet_pdk_installed
      failed_when: puppet_pdk_installed.rc > 1
      changed_when: puppet_pdk_installed.rc == 1

    - name: Install/uninstall Puppet and PDK
      block:

        - name: APT key and sources for Puppet
          apt:
            deb: '{{ puppet_package }}'
          when: puppet_pdk_installed.rc == 1 and not state == 'absent'

        - name: Puppet agent and development kit
          package:
            name:
              - puppet8-release
              - puppet-agent
              - pdk
            state: '{{ state }}'
            purge: yes
            update_cache: true

      become: true

  tags:
    - puppet

- name: Terraform
  snap:
    name: terraform
    classic: yes
    state: '{{ bool_state }}'
  become: true
  tags:
    - terraform
