---
# Software and configuration for automation ninjas

- name: Puppet development tool chain
  block:

  - name: Find out whether APT key and sources for PDK are installed
    command: dpkg-query -W puppet-release
    register: puppet_pdk_installed
    failed_when: puppet_pdk_installed.rc > 1
    changed_when: puppet_pdk_installed.rc == 1

  - name: APT key and sources for PDK
    apt:
      deb: https://apt.puppetlabs.com/puppet-release-{{ ansible_distribution_release }}.deb
      state: '{{ state }}'
    when: puppet_pdk_installed.rc == 1

  - name: Puppet developer packages
    package:
      name:
        - puppet
        - pdk
      state: '{{ state }}'
      update_cache: true

  become: true
  tags:
    - puppet

- name: Ansible developer packages
  package:
    name:
      - ansible
      - ansible-tower-cli
    state: '{{ state }}'
  tags:
    - ansible
