---
# Programmer's editors and IDEs

- name: Install Atom IDE
  community.general.snap:
    name: atom
    classic: yes
    state: present
  become: true
  tags:
    - atom

- name: VSCodium (freed version of Visual Studio Code)
  block:
    - block:
        - name: Add signing key of VSCodium package maintainer
          apt_key:
            url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
            state: present

        - name: Add APT source for VSCodium deb package
          apt_repository:
            repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/vscodium-archive-keyring.gpg] https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main'
            filename: vscodium
            update_cache: true
            state: present

        - name: Install VSCodium IDE
          package:
            name: codium
            state: present

      become: true

    - name: Install popular extensions for VSCodium (Visual Studio Code)
      command: codium --install-extension "{{ item }}" --force
      with_items: '{{ editors_vscode_plugins }}'

  tags:
    - vscode

- name: Install various JetBrains IDEs
  community.general.snap:
    name: '{{ item }}'
    classic: yes
    state: present
  loop: '{{ editors_jetbrains_ides }}'
  become: true
  tags:
    - jetbrains

- name: Ensure reasonably high file watch limit for JetBrains IDEs
  lineinfile:
    dest: /etc/sysctl.d/60-jetbrains.conf
    create: true
    line: '{{ item }}'
  with_items:
    - '# Set inotify watch limit high enough for IntelliJ IDEA (PhpStorm, PyCharm, RubyMine, WebStorm).'
    - '# Source: https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit'
    - 'fs.inotify.max_user_watches = 524288'
  become: true
  tags:
    - jetbrains
