---
# Programmer's editors and IDEs

- name: Atom IDE
  snap:
    name: atom
    classic: yes
    state: '{{ state }}'
  become: true
  tags:
    - atom

- name: Codium (freed version of Visual Studio Code)
  snap:
    name: codium
    classic: yes
    state: '{{ state }}'
  become: true
  tags:
    - codium
    - vscode

- name: Popular IDEs by JetBrains
  snap:
    name: '{{ item }}'
    classic: yes
    state: '{{ state }}'
  loop: '{{ editors_jetbrains_ides }}'
  become: true
  tags:
    - jetbrains

- name: Ensure reasonably high file watch limit for JetBrains IDEs
  lineinfile:
    dest: /etc/sysctl.d/60-jetbrains.conf
    create: true
    line: '{{ item }}'
  with_items:
    - '# Set inotify watch limit high enough for IntelliJ IDEA (PhpStorm, PyCharm, RubyMine, WebStorm).'
    - '# Source: https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit'
    - 'fs.inotify.max_user_watches = 524288'
  become: true
  tags:
    - jetbrains
