---
# Programmer's editors and IDEs

- name: Install Atom IDE
  command: snap install atom --classic
  become: true
  tags:
    - atom

- name: VSCodium (freed version of Visual Studio Code)
  block:

    - name: Find out whether VSCodium is installed
      command: dpkg-query -W vscodium
      register: vscodium_installed
      failed_when: vscodium_installed.rc > 1
      changed_when: vscodium_installed.rc == 1

    - name: Install VSCodium IDE
      apt: deb={{ vscodium_baseurl }}/{{ vscodium_package }}
      when: vscodium_installed.rc == 1 or force_upgrade == 'yes'
      become: true

    - name: Install popular extensions for VSCodium (Visual Studio Code)
      command: vscodium --install-extension "{{ item }}" --force
      with_items: '{{ editors_vscode_plugins }}'

  tags:
    - vscode

- name: Install various JetBrains IDEs
  command: snap install {{ item }} --classic
  with_items: '{{ editors_jetbrains_ides }}'
  become: true
  tags:
    - jetbrains

- name: Ensure reasonably high file watch limit for JetBrains IDEs
  lineinfile:
    dest: /etc/sysctl.d/60-jetbrains.conf
    create: true
    line: '{{ item }}'
  with_items:
    - '# Set inotify watch limit high enough for IntelliJ IDEA (PhpStorm, PyCharm, RubyMine, WebStorm).'
    - '# Source: https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit'
    - 'fs.inotify.max_user_watches = 524288'
  become: true
  tags:
    - jetbrains
