---
# Programmer's editors and IDEs

- name: Atom IDE
  snap:
    name: atom
    classic: yes
    state: '{{ state }}'
  become: true
  tags:
    - atom

- name: VSCodium (freed version of Visual Studio Code)
  block:

    - name: Codium IDE
      snap:
        name: codium
        classic: yes
        state: '{{ state }}'
      become: true

    - name: Popular extensions for Codium (Visual Studio Code)
      command: codium --install-extension "{{ item }}" --force
      loop: '{{ editors_vscode_plugins }}'
      when: state == 'present'

  tags:
    - codium
    - vscode

- name: Popular IDEs by JetBrains
  snap:
    name: '{{ item }}'
    classic: yes
    state: '{{ state }}'
  loop: '{{ editors_jetbrains_ides }}'
  become: true
  tags:
    - jetbrains

- name: Ensure reasonably high file watch limit for JetBrains IDEs
  lineinfile:
    dest: /etc/sysctl.d/60-jetbrains.conf
    create: true
    line: '{{ item }}'
  with_items:
    - '# Set inotify watch limit high enough for IntelliJ IDEA (PhpStorm, PyCharm, RubyMine, WebStorm).'
    - '# Source: https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit'
    - 'fs.inotify.max_user_watches = 524288'
  become: true
  tags:
    - jetbrains
