---
# Google's Go language and tooling

- block:

    - name: Install Go and Go tools
      snap:
        name: '{{ item }}'
        classic: yes
        state: '{{ bool_state }}'
      loop:
        - go
        - goreleaser
      become: true

    - name: Configure PATH to local Go binaries (Bash)
      blockinfile:
        path: '{{ ansible_env.HOME }}/.bash_aliases'
        block: |
          export PATH="{{ ansible_env.HOME }}/go/bin:$PATH"
        create: true
        state: '{{ bool_state }}'

  tags:
    - golang
