---
# Google's Go language and tooling

- block:

    - name: Install Go and Go tools
      snap:
        name: '{{ item }}'
        classic: yes
        state: '{{ bool_state }}'
      loop:
        - go
        - goreleaser
      become: true

    - name: Configure PATH to local Go binaries (Bash)
      lineinfile:
        dest: '{{ ansible_env.HOME }}/.bash_aliases'
        create: true
        line: '{{ item }}'
        state: '{{ bool_state }}'
      with_items:
        - 'export PATH="{{ ansible_env.HOME }}/go/bin:$PATH"'

  tags:
    - golang
