---
# JavaScript development tools and configuration

- block:

    - name: Install Node.js
      package:
        name:
          - nodejs
          - npm
        state: '{{ state }}'
      become: true

    - name: Activate Bash autocompletion for npm
      blockinfile:
        path: '{{ ansible_env.HOME }}/.bash_aliases'
        block: |
          which npm > /dev/null && {
            source <(npm completion)
          }
        create: true
        state: '{{ bool_state }}'

  tags:
    - nodejs
