---
# JavaScript development tools and configuration

- name: Install Node.js
  package:
    name:
      - nodejs
      - npm
    state: present
  become: true
  tags:
    - nodejs

- name: Activate Bash autocompletion for npm
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.bash_aliases'
    create: true
    line: 'source <(npm completion)'
  tags:
    - nodejs
