---
# Python tools and configuration (favoring Python 3, as it should be)

- name: Python developer tooling
  block:

    - name: Remove Python 2 Package Installer (pip)
      package:
        name: python-pip
        state: absent
        purge: yes
      become: true

    - name: Install Python 3 Package Installer (pip)
      package:
        name:
          - python3-pip
        state: present
      become: true

    - name: Activate Bash autocompletion for pip
      lineinfile:
        dest: '{{ ansible_env.HOME }}/.bash_aliases'
        create: true
        line: 'source <(pip3 completion --bash)'

    - name: Install Pipenv (Pip + Virtualenv)
      pip:
        name: pipenv
        state: present
      become: true

    - name: Clone pyenv (Python version management)
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: '{{ ansible_env.HOME }}/.pyenv'
        depth: 1

    - name: Activate pyenv for Bash
      lineinfile:
        dest: '{{ ansible_env.HOME }}/.bash_aliases'
        create: true
        line: '{{ item }}'
      with_items:
        - 'export PYENV_ROOT={{ ansible_env.HOME }}/.pyenv'
        - 'export PATH="$PYENV_ROOT/bin:$PATH"'
        - 'source <(pyenv init --path)'

    # See: https://github.com/pyenv/pyenv/wiki/Common-build-problems
    - name: Ensure dependencies for installing other Pythons (pyenv)
      package:
        name:
          - libbz2-dev
          - libffi-dev
          - libreadline-dev
          - libsqlite3-dev
          - libssl-dev
          - zlib1g-dev
        state: present
      become: true

  tags:
    - python
