---
# Python tools and configuration (favoring Python 3, as it should be)

- name: Remove Python 2 Package Installer (pip)
  package:
    name: python-pip
    state: absent
  become: true
  tags:
    - python

- name: Install Python 3 Package Installer (pip)
  package:
    name:
      - python3-pip
    state: present
  become: true
  tags:
    - python

- name: Activate Bash autocompletion for pip
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.bash_aliases'
    create: true
    line: 'source <(pip3 completion --bash)'
  tags:
    - python

- name: Install Pipenv (Pip + Virtualenv)
  pip:
    name: pipenv
    executable: pip3
    state: present
  become: true
  tags:
    - python

- name: Clone pyenv (Python version management)
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: '{{ ansible_env.HOME }}/.pyenv'
    depth: 1
  tags:
    - python

- name: Activate pyenv for Bash
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.bash_aliases'
    create: true
    line: '{{ item }}'
  with_items:
    - 'export PYENV_ROOT={{ ansible_env.HOME }}/.pyenv'
    - 'export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'source <(pyenv init --path)'
  tags:
    - bash
    - python

# See: https://github.com/pyenv/pyenv/wiki/Common-build-problems
- name: Ensure dependencies for installing other Pythons (pyenv)
  package:
    name:
      - libbz2-dev
      - libffi-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - zlib1g-dev
    state: present
  become: true
  tags:
    - python
