---
# Rust tools and configuration

- name: Install Rust toolchain
  package:
    name:
      - cargo
    state: present
  become: true
  tags:
    - rust

- name: Adjust PATH for Rust binaries built by Cargo
  blockinfile:
    path: '{{ ansible_env.HOME }}/.bash_aliases'
    marker: "# {mark} RUST"
    block: |
      export PATH="{{ ansible_env.HOME }}/.cargo/bin:$PATH"
    create: true
  tags:
    - bash
    - rust
