---
# Software for your communication needs

- name: Cryptography, calendar and tasks support for Thunderbird
  package: name={{ item }} state=present
  with_items:
    - enigmail
    - xul-ext-lightning
  become: true
  tags:
    - email

- block:
  - name: Add PPA for Geary email client
    apt_repository: repo=ppa:geary-team/releases state=present
  - name: Lightweight email client for GNOME
    package: name=geary state=present
  become: true
  tags:
    - email

- name: Install popular chat clients (snaps)
  command: snap install {{ item }} --classic
  with_items:
    - skype
    - slack
  become: true
  tags:
    - skype
    - slack

- name: Find out whether Rocket.Chat+ is installed
  command: dpkg-query -W rocketchat
  register: rocketchat_installed
  failed_when: rocketchat_installed.rc > 1
  changed_when: rocketchat_installed.rc == 1
  tags:
    - rocketchat

- name: Install Rocket.Chat+ client
  apt: deb=https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.14.0/rocketchat_2.14.0_amd64.deb
  when: rocketchat_installed.rc == 1 or force_upgrade == 'yes'
  become: true
  tags:
    - rocketchat

- name: Find out whether Franz multi-messenger is installed
  command: dpkg-query -W franz
  register: franz_installed
  failed_when: franz_installed.rc > 1
  changed_when: franz_installed.rc == 1
  tags:
    - franz

- name: Install Franz multi-messenger
  apt: deb=https://github.com/meetfranz/franz/releases/download/v5.0.0-beta.18/franz_5.0.0-beta.18_amd64.deb
  when: franz_installed.rc == 1 or force_upgrade == 'yes'
  become: true
  tags:
    - franz

- name: Find out whether Rambox multi-messenger is installed
  command: dpkg-query -W rambox
  register: rambox_installed
  failed_when: rambox_installed.rc > 1
  changed_when: rambox_installed.rc == 1
  tags:
    - rambox

- name: Install Rambox multi-messenger
  apt: deb=https://github.com/ramboxapp/community-edition/releases/download/0.6.1/Rambox-0.6.1-linux-amd64.deb
  when: rambox_installed.rc == 1 or force_upgrade == 'yes'
  become: true
  tags:
    - rambox

- name: Find out whether Zoom conferencing client is installed
  command: dpkg-query -W zoom
  register: zoom_installed
  failed_when: zoom_installed.rc > 1
  changed_when: zoom_installed.rc == 1
  tags:
    - zoom

- name: Install Zoom conferencing client
  apt: deb=https://zoom.us/client/latest/zoom_amd64.deb
  when: zoom_installed.rc == 1 or force_upgrade == 'yes'
  become: true
  tags:
    - zoom
