---
# Software for your communication needs

- name: Install popular chat clients (snaps)
  command: snap install {{ item }} --classic
  with_items:
    - skype
    - slack
  become: true

- name: Find out whether Rocket.Chat+ is installed
  command: dpkg-query -W rocketchat
  register: rocketchat_installed
  failed_when: rocketchat_installed.rc > 1
  changed_when: rocketchat_installed.rc == 1

- name: Install Rocket.Chat+ client
  apt: deb=https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.10.5/rocketchat_2.10.5_amd64.deb
  when: rocketchat_installed.rc == 1
  become: true

- name: Find out whether Franz multi-messenger is installed
  command: dpkg-query -W franz
  register: franz_installed
  failed_when: franz_installed.rc > 1
  changed_when: franz_installed.rc == 1

- name: Install Franz multi-messenger
  apt: deb=https://github.com/meetfranz/franz/releases/download/v5.0.0-beta.17/franz_5.0.0-beta.17_amd64.deb
  when: franz_installed.rc == 1
  become: true

- name: Find out whether Rambox multi-messenger is installed
  command: dpkg-query -W rambox
  register: rambox_installed
  failed_when: rambox_installed.rc > 1
  changed_when: rambox_installed.rc == 1

- name: Install Rambox multi-messenger
  apt: deb=https://github.com/saenzramiro/rambox/releases/download/0.5.16/Rambox_0.5.16-x64.deb
  when: rambox_installed.rc == 1
  become: true

- name: Cryptography support (for mail clients)
  package: name=enigmail state=present
  become: true
