---
# The base system (of a modern Linux distribution)

- name: Update APT cache before starting
  apt: update_cache=yes upgrade=no
  become: true

- import_tasks: desktop.yml
- import_tasks: webbrowsers.yml
- import_tasks: communication.yml
- import_tasks: tablet.yml
