---
# Software for image manipulation, video editing, audio conversion, etc.

- block:

    - name: The GIMP (incl. plugins)
      flatpak:
        name: '{{ item }}'
        state: '{{ bool_state }}'
      loop:
        - org.gimp.GIMP
        - org.gimp.GIMP.Plugin.GMic//{{ gimp_gmic_branch }}

    - name: Image and video conversion tools
      package:
        name:
          - imagemagick
          - trimage
        state: '{{ state }}'

    - name: Inkscape vector graphics
      package:
        name: inkscape
        state: '{{ state }}'

  become: true
  tags:
    - image-editing
    - multimedia

- name: PlantUML & Graphviz (diagrams from source code)
  package:
    name: plantuml
    state: '{{ state }}'
  become: true
  tags:
    - drawing
