---
# Software for image manipulation, video editing, audio conversion, etc.

- block:
  - name: Enable PPA for newer GIMP
    apt_repository:
      repo: ppa:otto-kesselgulasch/gimp
      state: '{{ bool_state }}'

  - name: Install image and video conversion tools
    package:
      name:
        - imagemagick
        - trimage
      state: '{{ state }}'

  - name: Install image manipulation programs
    package:
      name:
        - gimp-gmic
        - inkscape
      state: '{{ state }}'

  become: true
  tags:
    - image-editing
    - multimedia
