---
# Software for image manipulation, video editing, audio conversion, etc.

- name: Install image and video conversion tools
  package:
    name:
      - imagemagick
    state: present
  become: true
  tags:
    - image-editing
    - multimedia

- name: Install image manipulation programs
  package:
    name:
      - gimp
      - inkscape
    state: present
  become: true
  tags:
    - image-editing
    - multimedia
