---
# Software for image manipulation, video editing, audio conversion, etc.

- block:
  - name: Enable PPA for newer GIMP
    apt_repository:
      repo: ppa:otto-kesselgulasch/gimp
      state: present

  - name: Install image and video conversion tools
    package:
      name:
        - imagemagick
      state: present

  - name: Install image manipulation programs
    package:
      name:
        - gimp
        - inkscape
      state: present

  become: true
  tags:
    - image-editing
    - multimedia
