---
# Software for image manipulation, video editing, audio conversion, etc.

- block:

    - name: The GIMP
      flatpak:
        name: org.gimp.GIMP
        state: '{{ bool_state }}'

    - name: GREYC's Magic for Image Computing
      flatpak:
        name: org.gimp.GIMP.Plugin.GMic//{{ gimp_gmic_branch }}
        state: '{{ bool_state }}'

    - name: Image and video conversion tools
      package:
        name:
          - imagemagick
          - trimage
        state: '{{ state }}'

    - name: Inkscape vector graphics
      package:
        name: inkscape
        state: '{{ state }}'

  become: true
  tags:
    - image-editing
    - multimedia
