---
# Software for music consumption

- name: Install proprietary music players
  snap:
    name: spotify
    state: present
  become: true
  tags:
    - multimedia
    - music-listening

- name: Install LMMS music composing studio
  package:
    name: lmms
    state: present
  become: true
  tags:
    - multimedia
    - music-composing

- name: Install Audacity audio editor
  snap:
    name: audacity
    state: present
  become: true
  tags:
    - multimedia
    - music-editing
