---
# Software for music consumption

- name: Music editors and players
  block:

    - name: Spotify music player
      snap:
        name: spotify
        state: '{{ bool_state }}'
      become: true
      tags:
        - music-listening

    - name: LMMS music composing studio
      package:
        name: lmms
        state: '{{ state }}'
      become: true
      tags:
        - music-composing

    - name: Audacity audio editor
      snap:
        name: audacity
        state: '{{ bool_state }}'
      become: true
      tags:
        - music-editing

  tags:
    - multimedia
