---
# Software for video editing, audio conversion, etc.

- name: Video software
  block:

    - name: OpenShot video editor
      package:
        name: openshot-qt
        state: '{{ state }}'
      become: true
      tags:
        - video-editing

    - name: GNOME Video player (flatpak)
      flatpak:
        name: org.gnome.Totem
        state: '{{ bool_state }}'
      become: true
      tags:
        - gnome
        - video-watching

    - name: Video conversion tools and codecs
      package:
        name:
          - ffmpeg
          - ubuntu-restricted-extras
        state: '{{ state }}'
      become: true
      tags:
        - video-watching

    - name: yt-dlp (YouTube downloader)
      pip:
        name: yt-dlp
        state: '{{ state }}'
      become: true
      tags:
        - music-listening
        - video-watching

    - name: YouTube downloader defaults for music extraction
      lineinfile:
        dest: '{{ ansible_env.HOME }}/.config/yt-dlp/config'
        create: true
        line: '{{ item }}'
        state: '{{ bool_state }}'
      with_items:
        - '--extract-audio'
        - '--audio-format mp3'
        - '--add-metadata'
      tags:
        - music-listening

  tags:
    - multimedia
