---
# Software for image manipulation, video editing, audio conversion, etc.

- name: Install video conversion tools
  package:
    name:
      - ffmpeg
    state: present
  become: true
  tags:
    - multimedia

- name: Install YouTube downloader
  pip:
    name: youtube-dl
    state: latest
    executable: pip3
    extra_args: --user
  tags:
    - multimedia

- name: Set YouTube downloader defaults for music extraction
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.config/youtube-dl/config'
    create: true
    line: '{{ item }}'
  with_items:
    - '--extract-audio'
    - '--audio-format mp3'
    - '--add-metadata'
  tags:
    - multimedia
